### ISSUE TITLE
Add libre license

### ISSUE THREAD

**Issue by throwaway1037** [ron-rs/ron.vim#6]
This project is proprietary until a libre license is added.

**Comment by throwaway1037** [comment]
Anyone there?

**Comment by savchenko** [comment]
@derwiath / andreas@neoboid.com ?

**Comment by derwiath** [comment]
I don’t mind, but this isn’t my repo. Maybe @torkleyy can help out.

**Comment by LukasDoesDev** [comment]
I've been using the Rust syntax highlighting with an autocmd:
```vim
autocmd BufRead *.ron set syntax=rust
```

**Comment by torkleyy** [comment]
Fixed

**Comment by throwaway1037** [comment]
Thank you.
The best practise is to put a license header at the top of each file, because a lone license in the root of the project doesn't mean much on its own.
